/**
 * team.js — multi-seat enterprise management — Phase 9.2 of BUILD_ROADMAP.md.
 *
 * Endpoints (all under /be/team/*, all signed-in-user-only)
 *
 *   GET    /be/team/list                       my teams + my role + member count
 *   POST   /be/team/create                     { name, plan?, seats? }   creator becomes owner
 *   GET    /be/team/{id}/members               members of that team (RLS-scoped)
 *   POST   /be/team/{id}/invite                { email, role? }          sends email
 *   GET    /be/team/{id}/invitations           pending invites (admin/owner only)
 *   POST   /be/team/accept                     { token }                 join via invitation
 *   POST   /be/team/{id}/leave                 leave the team (owners can't leave directly)
 *   DELETE /be/team/{id}/member/{userId}       remove someone (admin/owner only)
 *
 * Auth model
 * ----------
 * The Worker resolves auth.userId from the Supabase JWT and uses the
 * service-role key to read/write. RLS still applies to direct REST
 * reads from the BROWSER but the Worker bypasses RLS — so every
 * mutation here checks role/membership in code before doing the write.
 *
 * Invitations
 * -----------
 * INSERT into team_invitations fires a pg_net trigger that emails the
 * invitee via Resend with a link to /accept-invite.html?token=<token>.
 * The token is a 32-byte hex string generated by the Worker.
 */
import { json, badRequest, unauthorized } from '../lib/responses.js';
import { sbService } from '../lib/supabase.js';

// ── helpers ─────────────────────────────────────────────────────────

function clean(s, max) {
  const v = String(s ?? '').normalize('NFKC').trim();
  return max ? v.slice(0, max) : v;
}

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

/** Random URL-safe 32-byte (64-char) hex token using Web Crypto. */
function generateInviteToken() {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join('');
}

/** Look up my role on a team. Returns 'owner' | 'admin' | 'member' | null. */
async function getMyRole(env, teamId, userId) {
  const r = await sbService(
    env,
    `/team_members?team_id=eq.${encodeURIComponent(teamId)}&user_id=eq.${encodeURIComponent(userId)}&select=role&limit=1`
  );
  if (!r.ok) return null;
  const arr = await r.json();
  return Array.isArray(arr) && arr.length ? arr[0].role : null;
}

function canAdmin(role) {
  return role === 'owner' || role === 'admin';
}

// ── /be/team/list ─────────────────────────────────────────────────

export async function handleTeamList(auth, env) {
  if (auth.kind !== 'user') return unauthorized();
  const r = await sbService(env, '/rpc/list_my_teams', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ uid: auth.userId }),
  });
  if (!r.ok) return json({ teams: [] });
  return json({ teams: await r.json() });
}

// ── /be/team/create ───────────────────────────────────────────────

export async function handleTeamCreate(request, auth, env) {
  if (auth.kind !== 'user') return unauthorized();
  let body;
  try { body = await request.json(); } catch { return badRequest('invalid_json'); }
  const name  = clean(body.name, 120);
  const plan  = clean(body.plan, 20).toLowerCase() || 'enterprise';
  const seats = Math.max(1, Math.min(parseInt(body.seats, 10) || 5, 500));
  if (!name) return badRequest('missing_name');
  if (!['starter', 'professional', 'business', 'enterprise'].includes(plan)) {
    return badRequest('invalid_plan');
  }

  const r = await sbService(env, '/teams', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Prefer: 'return=representation' },
    body: JSON.stringify({ name, plan, seats, owner_user_id: auth.userId }),
  });
  if (!r.ok) {
    const detail = (await r.text()).slice(0, 300);
    return json({ error: 'create_failed', detail }, 500);
  }
  const arr = await r.json();
  // Trigger _teams_seed_owner_member fires the owner membership row.
  return json({ team: arr[0] });
}

// ── /be/team/{id}/members ─────────────────────────────────────────

export async function handleTeamMembers(teamId, auth, env) {
  if (auth.kind !== 'user') return unauthorized();
  const role = await getMyRole(env, teamId, auth.userId);
  if (!role) return json({ error: 'not_a_member' }, 403);
  // Join to auth.users to surface the email — admin.users via service_role
  // is allowed but PostgREST can't dereference it directly, so we do two
  // queries and merge. At <500 seats / team this is fine.
  const memR = await sbService(
    env,
    `/team_members?team_id=eq.${encodeURIComponent(teamId)}&select=user_id,role,joined_at&order=joined_at.asc`
  );
  if (!memR.ok) return json({ error: 'db_error' }, 500);
  const members = await memR.json();
  if (!members.length) return json({ members: [] });

  // Hydrate emails from profiles (we always have a profiles row per user).
  const ids = members.map(m => `"${m.user_id}"`).join(',');
  const profR = await sbService(
    env,
    `/profiles?id=in.(${ids})&select=id,email,full_name`
  );
  let profiles = [];
  if (profR.ok) {
    profiles = await profR.json();
    if (!Array.isArray(profiles)) profiles = [];
  }
  const byId = Object.fromEntries(profiles.map(p => [p.id, p]));
  const out = members.map(m => ({
    user_id: m.user_id,
    role: m.role,
    joined_at: m.joined_at,
    email: byId[m.user_id]?.email || null,
    full_name: byId[m.user_id]?.full_name || null,
  }));
  return json({ members: out, my_role: role });
}

// ── /be/team/{id}/invite ──────────────────────────────────────────

export async function handleTeamInvite(teamId, request, auth, env) {
  if (auth.kind !== 'user') return unauthorized();
  const role = await getMyRole(env, teamId, auth.userId);
  if (!canAdmin(role)) return json({ error: 'forbidden' }, 403);

  let body;
  try { body = await request.json(); } catch { return badRequest('invalid_json'); }
  const email = clean(body.email, 320).toLowerCase();
  const inviteRole = clean(body.role, 20).toLowerCase() || 'member';
  if (!EMAIL_RE.test(email)) return badRequest('invalid_email');
  if (!['admin', 'member'].includes(inviteRole)) return badRequest('invalid_role');

  // Reject if already a member.
  const existR = await sbService(
    env,
    `/profiles?email=eq.${encodeURIComponent(email)}&select=id&limit=1`
  );
  let existingUserId = null;
  if (existR.ok) {
    const arr = await existR.json();
    if (Array.isArray(arr) && arr.length) existingUserId = arr[0].id;
  }
  if (existingUserId) {
    const mineR = await sbService(
      env,
      `/team_members?team_id=eq.${encodeURIComponent(teamId)}&user_id=eq.${encodeURIComponent(existingUserId)}&select=user_id&limit=1`
    );
    if (mineR.ok) {
      const arr = await mineR.json();
      if (Array.isArray(arr) && arr.length) {
        return json({ error: 'already_member' }, 409);
      }
    }
  }

  // De-dupe pending invitations on the same email.
  const pendR = await sbService(
    env,
    `/team_invitations?team_id=eq.${encodeURIComponent(teamId)}&email=eq.${encodeURIComponent(email)}&accepted_at=is.null&select=id&limit=1`
  );
  if (pendR.ok) {
    const arr = await pendR.json();
    if (Array.isArray(arr) && arr.length) {
      return json({ error: 'already_invited' }, 409);
    }
  }

  // Seat limit check: count current members + pending invites.
  const seatR = await sbService(
    env,
    `/teams?id=eq.${encodeURIComponent(teamId)}&select=seats`
  );
  const seatArr = seatR.ok ? await seatR.json() : [];
  const seats = Array.isArray(seatArr) && seatArr.length ? Number(seatArr[0].seats) : 0;
  if (seats > 0) {
    // Count members and pending invites separately and compare.
    const [memCntR, invCntR] = await Promise.all([
      sbService(env, `/team_members?team_id=eq.${encodeURIComponent(teamId)}&select=user_id`, {
        headers: { Prefer: 'count=exact', Range: '0-0' },
      }),
      sbService(env, `/team_invitations?team_id=eq.${encodeURIComponent(teamId)}&accepted_at=is.null&select=id`, {
        headers: { Prefer: 'count=exact', Range: '0-0' },
      }),
    ]);
    const memCount = parseInt((memCntR.headers.get('content-range') || '0-0/0').split('/').pop(), 10) || 0;
    const invCount = parseInt((invCntR.headers.get('content-range') || '0-0/0').split('/').pop(), 10) || 0;
    if (memCount + invCount >= seats) {
      return json({ error: 'seat_limit_reached', seats }, 409);
    }
  }

  const token = generateInviteToken();
  const insR = await sbService(env, '/team_invitations', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Prefer: 'return=representation' },
    body: JSON.stringify({
      team_id: teamId,
      email,
      role: inviteRole,
      token,
      invited_by: auth.userId,
    }),
  });
  if (!insR.ok) {
    const detail = (await insR.text()).slice(0, 300);
    return json({ error: 'invite_failed', detail }, 500);
  }
  const arr = await insR.json();
  // Email is sent automatically by the notify_team_invitee pg_net trigger.
  return json({
    invitation: { id: arr[0].id, email, role: inviteRole, expires_at: arr[0].expires_at },
  });
}

// ── /be/team/{id}/invitations ────────────────────────────────────

export async function handleTeamInvitations(teamId, auth, env) {
  if (auth.kind !== 'user') return unauthorized();
  const role = await getMyRole(env, teamId, auth.userId);
  if (!canAdmin(role)) return json({ error: 'forbidden' }, 403);
  const r = await sbService(
    env,
    `/team_invitations?team_id=eq.${encodeURIComponent(teamId)}&accepted_at=is.null&select=id,email,role,expires_at,created_at&order=created_at.desc`
  );
  if (!r.ok) return json({ invitations: [] });
  return json({ invitations: await r.json() });
}

// ── /be/team/accept ──────────────────────────────────────────────

export async function handleTeamAccept(request, auth, env) {
  if (auth.kind !== 'user') return unauthorized();
  let body;
  try { body = await request.json(); } catch { return badRequest('invalid_json'); }
  const token = clean(body.token, 200);
  if (!token) return badRequest('missing_token');

  const r = await sbService(
    env,
    `/team_invitations?token=eq.${encodeURIComponent(token)}&select=id,team_id,email,role,expires_at,accepted_at&limit=1`
  );
  if (!r.ok) return json({ error: 'db_error' }, 500);
  const arr = await r.json();
  const inv = Array.isArray(arr) && arr.length ? arr[0] : null;
  if (!inv) return json({ error: 'invalid_token' }, 404);
  if (inv.accepted_at) return json({ error: 'already_accepted' }, 409);
  if (new Date(inv.expires_at).getTime() < Date.now()) return json({ error: 'expired' }, 410);

  // Match by email (case-insensitive) so a user can't accept someone
  // else's invite. The Worker has auth.email available; profiles row
  // can be checked too as a fallback.
  if (auth.email && inv.email && auth.email.toLowerCase() !== inv.email.toLowerCase()) {
    return json({ error: 'email_mismatch', invited_email: inv.email }, 403);
  }

  // Insert membership (idempotent via PK).
  const memR = await sbService(env, '/team_members', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Prefer: 'resolution=merge-duplicates' },
    body: JSON.stringify({ team_id: inv.team_id, user_id: auth.userId, role: inv.role }),
  });
  if (!memR.ok && memR.status !== 409) {
    const detail = (await memR.text()).slice(0, 300);
    return json({ error: 'join_failed', detail }, 500);
  }

  // Mark invitation accepted.
  await sbService(env, `/team_invitations?id=eq.${encodeURIComponent(inv.id)}`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', Prefer: 'return=minimal' },
    body: JSON.stringify({ accepted_at: new Date().toISOString() }),
  });

  return json({ ok: true, team_id: inv.team_id, role: inv.role });
}

// ── /be/team/{id}/leave ──────────────────────────────────────────

export async function handleTeamLeave(teamId, auth, env) {
  if (auth.kind !== 'user') return unauthorized();
  const role = await getMyRole(env, teamId, auth.userId);
  if (!role) return json({ error: 'not_a_member' }, 404);
  if (role === 'owner') {
    return json({ error: 'owner_cannot_leave', detail: 'Transfer ownership or delete the team first.' }, 409);
  }
  const r = await sbService(
    env,
    `/team_members?team_id=eq.${encodeURIComponent(teamId)}&user_id=eq.${encodeURIComponent(auth.userId)}`,
    { method: 'DELETE' }
  );
  if (!r.ok) return json({ error: 'leave_failed' }, 500);
  return json({ ok: true });
}

// ── /be/team/{id}/member/{userId}  (DELETE) ─────────────────────

export async function handleTeamRemoveMember(teamId, targetUserId, auth, env) {
  if (auth.kind !== 'user') return unauthorized();
  const myRole = await getMyRole(env, teamId, auth.userId);
  if (!canAdmin(myRole)) return json({ error: 'forbidden' }, 403);
  if (targetUserId === auth.userId) {
    return json({ error: 'use_leave_endpoint' }, 409);
  }
  const targetRole = await getMyRole(env, teamId, targetUserId);
  if (targetRole === 'owner') {
    return json({ error: 'cannot_remove_owner' }, 409);
  }
  const r = await sbService(
    env,
    `/team_members?team_id=eq.${encodeURIComponent(teamId)}&user_id=eq.${encodeURIComponent(targetUserId)}`,
    { method: 'DELETE' }
  );
  if (!r.ok) return json({ error: 'remove_failed' }, 500);
  return json({ ok: true });
}
